---
title: "Readme.md"
subtitle: Getting and Cleanning Data Course Project
---

The script run_analysis.R was created to execute the different tasks involved in order to generated the two tidy data sets required in the project's instructions.

Project Instructions
-------------------------------------------------------

Create one R script called run_analysis.R that does the following.

* Merges the training and the test sets to create one data set.
* Extracts only the measurements on the mean and standard deviation for each measurement. 
* Uses descriptive activity names to name the activities in the data set
* Appropriately labels the data set with descriptive variable names. 
* Creates a second, independent tidy data set with the average of each variable for each activity and each subject. 

Instructions for running the script
-------------------------------------------------------

1. Set the working directory to the root the directory that contains the unpacked folders from the zip file: getdata-projectfiles-UCI HAR Dataset.zip. For example: setwd("~/Documents/Coursera/Getting and Cleaning Data") were the folder "Getting and Cleaning Data" contains the data folder: UCI HAR Dataset.
2. Run the code: source('~/Documents/Coursera/Getting and Cleaning Data/run_analysis.R', echo=TRUE). This will execute the script. You could also load the code and simply execute by entering: run_analysis in the console.
3. Load library(data.table)

Script explanation
-------------------------------------------------------
##Read data and create first tidy data set.

- Load files - The following files are loaded into memory:

TEST
The following data frames are created:

* x-test - features
* y_test - activity
* sub_test - subject

TRAIN
The following data frames are created:
* x_train 
* y_train
* sub_train

- Combine subject, activity and features data into a test and training

###First objective
- Merges the training and the test sets to create one data set.
* sub
* x
* y
* data

###Second objective
Extracts only the measurements on the mean and standard deviation for each measurement.
* x

###Third objective
- Uses descriptive activity names to name the activities in the data set


###Four objective
- Appropriately labels the data set with descriptive variable names.
- Exports first tidy data set to file system "merged_data.txt"

##Create second tidy data set
- Creates a second, independent tidy data set with the average of each variable for each activity and each subject.
- Create a copy of the first tidy data structure. Then iterate the first data set, "merged_data.txt", and insert into new data set the average of features for for each activity by subject. The result will data frame of 180 observations and 68 variables.

- Exports second tidy data set to file system with the average of each variable for each activity and each subject.